# Generated by Django 3.1.7 on 2021-03-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribbon', '0002_auto_20210316_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='order_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_total',
            field=models.FloatField(default=0),
        ),
    ]
