# Generated by Django 3.1.7 on 2021-03-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribbon', '0003_auto_20210316_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='New', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='region',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
