# Generated by Django 3.1.7 on 2021-03-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribbon', '0004_auto_20210316_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Ожидание', 'Ожидание'), ('Доставлен', 'Доставлен')], default='Новый', max_length=200, null=True),
        ),
    ]
