# Generated by Django 3.1.7 on 2021-03-16 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ribbon', '0006_auto_20210316_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='house',
            new_name='apartment',
        ),
    ]
