# Generated by Django 3.1.7 on 2021-03-16 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ribbon', '0007_auto_20210316_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
