# Generated by Django 3.1.7 on 2021-03-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribbon', '0008_orderinfo_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='customer_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.CharField(blank=True, choices=[('Новый', 'Новый'), ('Обработан', 'Обработан'), ('Доставлен', 'Доставлен')], default='Новый', max_length=200, null=True),
        ),
    ]
