# Generated by Django 3.1.7 on 2021-03-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribbon', '0009_auto_20210318_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ribbon',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
